#FROM hypriot/rpi-golang:latest
FROM golang:latest

RUN mkdir -p /go/src/hello && mkdir /artifacts

COPY hello.go /go/src/hello/main.go

COPY Dockerfile /artifacts/Dockerfile

CMD GOPATH=/go go build -o /artifacts/hello hello
